### ISSUE TITLE
TextEditor.scopesForBufferPosition is deprecated.

### ISSUE THREAD

**Issue by parir** [yasuyuky/autocomplete-clang#51] opened 2015-04-19 14:14 UTC
Use ::scopeDescriptorForBufferPosition instead. The return value has changed! It now returns a  ScopeDescriptor      TextEditor.scopesForBufferPosition  /opt/atom/resources/app/src/text-editor.js:2840:7  Object.getFirstCursorScopes  /home/peer/.atom/packages/autocomplete-clang/lib/util.coffee:20:22

**Comment by yasuyuky** [comment] 2015-04-20 00:03
Duplicate of duplicate of #36, #47, #49. 
Fixed in v0.6.5. Thanks

**Closed by yasuyuky** 2015-04-20 00:03 UTC
