### ISSUE TITLE
TextEditor.scopesForBufferPosition is deprecated.

### ISSUE THREAD

**Issue by sajingeo** [yasuyuky/autocomplete-clang#49] opened 2015-04-14 17:12 UTC
Use ::scopeDescriptorForBufferPosition instead. The return value has changed! It now returns a `ScopeDescriptor`
```
TextEditor.scopesForBufferPosition (C:\Users\Sajin\AppData\Local\atom\app-0.190.0\resources\app\src\text-editor.js:2842:7)
Object.getFirstCursorScopes (C:\Users\Sajin\.atom\packages\autocomplete-clang\lib\util.coffee:20:22)
```

**Comment by yasuyuky** [comment] 2015-04-15 05:50
Thanks.  close because duplicate of #47

**Closed by yasuyuky** 2015-04-15 05:50 UTC
