### ISSUE TITLE
Clang-flags is referred to by Git, rather than release

### ISSUE THREAD

**Issue by Kev** [yasuyuky/autocomplete-clang#37] opened 2015-02-24 22:01 UTC
Hi, I just published a new (v0.2.1) release of clang-flags with all the fixes that've been put onto trunk. Would you like to now start referring to the 0.2.1 release of clang-flags, rather than pointing to Git master (It should be more resistant to me making changes to trunk that break things)? If so, I can sort out a PR. If not, feel free to close this issue!

**Comment by yasuyuky** [comment] 2015-03-17 16:46
Hi! thanks for the suggest.  

Because I'm not familiar to npm ecosystems, I can't find out which is better.
In the past version of package.json, the version of clang-flags referred the released version.
But some module incompatibility problems happened.
Could you tell me why the problems happened and pointing the released version is better?

**Comment by nanomad** [comment] 2015-03-18 12:40
Hi,

If you depend on a git "trunk" then Kev could potentially introduce api-breaking changes and break your package too. The buillds would also be non-reproducibile. 

Unless there are unreleased fixes in the clang-flags repo you depend on, it's better to depend on the latest stable npm version of the package (this is generally true for any package management sistem)

Nanomad

**Comment by yasuyuky** [comment] 2015-04-03 16:43
Thanks @nanomad 
I will use tagged clang-flags instead of git URL if the new version which eliminate dependency on "pathwatcher" released.

see https://github.com/Kev/clang-flags/pull/9 (This PR has been already merged.)

**Comment by Kev** [comment] 2015-04-06 08:06
I've just released 0.2.2 with your patch to remove the patchwatcher dependency.

**Comment by yasuyuky** [comment] 2015-04-07 03:08
Thank you. I've just updated package.json and released new version :+1:

**Closed by yasuyuky** 2015-04-07 03:08 UTC
